### ISSUE TITLE
Service Standard posters

### ISSUE THREAD

**Issue by htmlandbacon** [dwp/posters#4]
With the release of the updated service standard, I thought it would be good to create some posters to raise awareness of it?

@abbott567 @beckysarahlee @gavinelliott

**Comment by beckysarahlee** [comment]
Yes! @htmlandbacon I am happy to do this! alone... or with anyone who wants to help.

**Comment by htmlandbacon** [comment]
I guess, it might be easier to make some and take it from there?

**Comment by htmlandbacon** [comment]
Starter for 10, everything is good till you get to some of the longer points.

@beckysarahlee, @abbott567 

![01](https://user-images.githubusercontent.com/4334015/60596049-18eca180-9da0-11e9-9a49-35afbf82f01d.png)
![02](https://user-images.githubusercontent.com/4334015/60596050-19853800-9da0-11e9-8f07-badd71911c95.png)
![03](https://user-images.githubusercontent.com/4334015/60596051-19853800-9da0-11e9-996e-5c8c274b2bd4.png)
![04](https://user-images.githubusercontent.com/4334015/60596052-19853800-9da0-11e9-8d1c-d6c3629403f6.png)

**Comment by beckysarahlee** [comment]
Oooh! I did some before I left for holiday, but to be honest I like these more. Will show you the ones I did when I get back Monday.

**Comment by srich-DWP** [comment]
I like the colour scheme, very striking.
Not sure how it would print on the DWP colour printers though ?

**Comment by htmlandbacon** [comment]
> I like the colour scheme, very striking.
> Not sure how it would print on the DWP colour printers though ?

For the if you mean people one, I did colour + white version as I appreciate DWP printers may not be the best. 
https://github.com/dwp/posters/blob/master/people%20not%20resource/if-you-mean-people.pdf

I was pleasantly surprised we didn't have a style guide so I could roll some hot pink.

**Comment by beckysarahlee** [comment]
[Service standard posters.pdf](https://github.com/dwp/posters/files/3391689/Service.standard.posters.pdf)

**Comment by srich-DWP** [comment]
Nice @beckysarahlee I've downloaded these to put up in Leeds

**Comment by beckysarahlee** [comment]
Thanks @srich-DWP! Going to do one with all the points on... will hopefully get it done by the end of the week.

**Comment by srich-DWP** [comment]
@beckysarahlee are points 2 & 3 meant to be the same descriptor?

**Comment by beckysarahlee** [comment]
@srich-DWP Nope! But they have different ones now...

**Comment by beckysarahlee** [comment]
[Service standard posters.pdf](https://github.com/dwp/posters/files/3392742/Service.standard.posters.pdf)

**Comment by htmlandbacon** [comment]
> [Service standard posters.pdf](https://github.com/dwp/posters/files/3392742/Service.standard.posters.pdf)

Do you want to raise this as a pull request and get @abbott567 and @srich-DWP to proof them before merging?
