### ISSUE TITLE
Inclusive design posters

### ISSUE THREAD

**Issue by htmlandbacon** [dwp/posters#5]
I was reading this: https://www.designcouncil.org.uk/resources/guide/principles-inclusive-design

I'm not sure we have any inclusive design principles? If we have any though I'd love to see!

Not principles but I thought these are good snippets for some posters:

- Inclusive design is about making services everyone can use.
- Inclusive design is everyone's responsibility.
- Good design is inclusive design.

**Comment by abbott567** [comment]
Me and @gavinelliott were having a discussion about this literally the other day. We were talking about maybe calling it "what is good design" rather than design principles because we don't want to confuse them with the GOVUK ones.

**Comment by htmlandbacon** [comment]
I always kinda think of qualities/principles of being elements that make good design.

I guess the naming of it doesn't stop the underpinning.

Assuming inclusion is one of them?
